name: WebP Pixbuf CI [Fedora]
'on':
  push:
    branches:
      - mainline
  pull_request:
    branches:
      - mainline
jobs:
  Build:
    runs-on: fedora-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo dnf install gcc meson libwebp-devel gdk-pixbuf2-devel
      - run: mkdir build
      - run: meson build
      - run: ninja -C build
      - run: ninja -C build test
